# Generated by Django 2.2.4 on 2020-02-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=15)),
                ('description', models.CharField(default='none', max_length=50)),
                ('price', models.CharField(default='none', max_length=15)),
                ('university', models.CharField(default='none', max_length=25)),
                ('image1', models.FileField(upload_to='images/product')),
                ('image2', models.FileField(upload_to='images/product')),
                ('image3', models.FileField(upload_to='images/product')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AppUser')),
            ],
        ),
    ]
