# Generated by Django 2.2.4 on 2020-02-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(choices=[('christian', 'christian'), ('muslim', 'muslim'), ('none', 'none')], default='none', max_length=10)),
                ('department', models.CharField(default='none', max_length=50)),
                ('university', models.CharField(default='none', max_length=25)),
                ('hobbies', models.CharField(default='none', max_length=25)),
                ('host_name', models.CharField(default='none', max_length=25)),
                ('host_phone', models.CharField(default='none', max_length=25)),
                ('language', models.CharField(default='none', max_length=50)),
                ('apartment_name', models.CharField(default='none', max_length=50)),
                ('apartment_type', models.CharField(choices=[('hostel', 'hostel'), ('self contain', 'self contain'), ('single room self contain', 'single room self contain'), ('two rooms self contain', 'two rooms self contain'), ('one bedroom flat', 'one bedroom flat'), ('two bedroom flat', 'two bedroom flat'), ('three bedroom flat', 'three bedroom flat')], default='self contain', max_length=10)),
                ('address', models.CharField(default='none', max_length=50)),
                ('description', models.CharField(default='none', max_length=50)),
                ('landmarks', models.CharField(default='none', max_length=50)),
                ('photo', models.ImageField(default='', upload_to='images/')),
                ('duration_1', models.CharField(default='none', max_length=50)),
                ('duration_2', models.CharField(default='none', max_length=50)),
                ('image1', models.FileField(upload_to='images/unimate')),
                ('image2', models.FileField(upload_to='images/unimate')),
                ('image3', models.FileField(upload_to='images/unimate')),
                ('extras', models.CharField(default='none', max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMateHobbyConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=60)),
                ('reg_date', models.DateField(auto_now=True)),
                ('hobby', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='unimate.Hobby')),
                ('room_mate', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='unimate.RoomMate')),
            ],
        ),
    ]
