# Generated by Django 2.2.4 on 2020-02-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommate',
            name='unimate_no',
            field=models.CharField(default='none', max_length=5),
        ),
    ]
