# Generated by Django 2.2.4 on 2020-02-25 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('abbr', models.CharField(default='none', max_length=15)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=25)),
                ('religion', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('university', models.CharField(default='none', max_length=25)),
                ('language', models.CharField(default='none', max_length=25)),
                ('hobbies', models.CharField(default='none', max_length=25)),
                ('schoolidcard_image', models.ImageField(default='', upload_to='images/appuser')),
                ('voterscard_image', models.ImageField(default='', upload_to='images/appuser')),
                ('nationalidcard_image', models.ImageField(default='', upload_to='images/appuser')),
                ('driverslicence_image', models.ImageField(default='', upload_to='images/appuser')),
                ('photo', models.ImageField(default='', upload_to='images/appuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
