# Generated by Django 2.2.4 on 2020-03-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=25)),
                ('address', models.CharField(default='none', max_length=25)),
                ('university', models.CharField(default='none', max_length=25)),
                ('price', models.CharField(default='none', max_length=10)),
                ('apartment_type', models.CharField(choices=[('hostel', 'hostel'), ('self contain', 'self contain'), ('single room self contain', 'single room self contain'), ('two rooms self contain', 'two rooms self contain'), ('one bedroom flat', 'one bedroom flat'), ('two bedroom flat', 'two bedroom flat'), ('three bedroom flat', 'three bedroom flat')], default='self contain', max_length=30)),
                ('poster_phone', models.CharField(default='none', max_length=25)),
                ('poster_name', models.CharField(default='none', max_length=25)),
                ('image1', models.FileField(upload_to='images/rental')),
                ('image2', models.FileField(upload_to='images/rental')),
                ('image3', models.FileField(upload_to='images/rental')),
                ('image4', models.FileField(upload_to='images/rental')),
                ('image5', models.FileField(upload_to='images/rental')),
                ('landmarks', models.CharField(default='none', max_length=125)),
                ('motorcycle_fare', models.CharField(default='none', max_length=20)),
                ('vehicle_fare', models.CharField(default='none', max_length=20)),
                ('access_road_condi', models.CharField(choices=[('paved', 'paved'), ('unpaved', 'unpaved')], default='paved', max_length=10)),
                ('extras', models.CharField(default='none', max_length=100)),
                ('water', models.CharField(default='none', max_length=50)),
                ('security', models.CharField(default='none', max_length=50)),
                ('electricity', models.CharField(default='none', max_length=50)),
                ('kitchen', models.CharField(default='none', max_length=50)),
                ('avail_toilet', models.CharField(default='none', max_length=50)),
                ('bathroom', models.CharField(default='none', max_length=50)),
                ('avail_tiles', models.CharField(default='none', max_length=50)),
                ('running_water', models.CharField(default='none', max_length=50)),
                ('water_storage', models.CharField(default='none', max_length=50)),
                ('ceiling', models.CharField(default='none', max_length=50)),
                ('prepared_meter', models.CharField(default='none', max_length=50)),
                ('lodge_transformer', models.CharField(default='none', max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('walk_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentLandmarkConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=60)),
                ('reg_date', models.DateField(auto_now=True)),
                ('apartment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rental.Apartment')),
                ('landmark', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rental.Landmark')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImageConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=60)),
                ('reg_date', models.DateField(auto_now=True)),
                ('apartment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rental.Apartment')),
                ('image', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rental.Image')),
            ],
        ),
    ]
