# Generated by Django 2.2.4 on 2020-02-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('content_brief', models.CharField(default='', max_length=50)),
                ('content_main', models.CharField(default='', max_length=250)),
                ('tags', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.FileField(upload_to='images/blog')),
            ],
        ),
    ]
